### ISSUE TITLE
Application Form: Preferred Pronouns Bug

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/level-up#130]
When selecting `Other` one cannot specify a custom value even though the explanation text states it is possible:

`By picking "Other" you can specify a custom set of pronouns.`

**Comment by enrico-ghidoni** [comment]
This wasn't implemented due to lack of time and focus being on other features. Personally I'd take out the help text (the one saying that by picking "other" you can specify the pronouns) for the time being as it's not a critical feature.

What could fill the gap before the feature is implemented? Interviewer can ask the applicant what the preferred pronouns are and outline them in the recruit feedback on Enjin.

**Comment by enrico-ghidoni** [comment]
Merged with related issues into #133
